import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-l poppins-regular from-slate-100 to-amber-100`}>
        <NavBar />

        <main className="">
          {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
